### ISSUE TITLE
Rundll32.exe

### ISSUE THREAD

**Issue by Invisible40** [Jarmezrocks/Windows7GifViewer#3]
Windows 10 Home 64-bit. I can still open GIF files with the program, however whenever I try to open a GIF I always get an admin confirmation for "rundll32.exe". How can I get rid of the confirmations all the time?

**Comment by Jarmezrocks** [comment]
Hi @Superluigi6,
Unfortunately that message will never go away. This is because the executable rundll32 is actually a Windows XP signed exe and not a Windows 10 signed exe....and more so the fact that it needs to be executed in compatibility mode (which by design) triggers the UAC prompt that you are seeing. The only way that you or anyone will get rid of this is by not running the exe in compatibility mode (unfortunately not possible as far as I am aware?) or if you can "recode" the executable not to be reliant on the XP system and therefore not need to be executed in 'XP mode' and not triggering UAC (also not easily achieved and damn near impossible as far as I am aware).

**Comment by Invisible40** [comment]
Oh okay. Thanks anyways.
